# H2 in-memory
spring.datasource.url=jdbc:h2:mem:bookreviews;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=false

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Simple default user for HTTP Basic (since you didn't define a UserDetailsService)
spring.security.user.name=dev
spring.security.user.password=devpass
logging.level.org.springframework.security=DEBUG


# Flyway clean command for h2
#mvn `
#"-Dflyway.cleanDisabled=false" `
#"-Dflyway.url=jdbc:h2:file:$env:USERPROFILE/bookreviews-dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH" `
#"-Dflyway.user=sa" `
#"-Dflyway.password=" `
#flyway:clean
#
# Flyway migrate command for h2
#mvn `
#"-Dflyway.url=jdbc:h2:file:$env:USERPROFILE/bookreviews-dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH" `
#"-Dflyway.user=sa" `
#"-Dflyway.password=" `
#flyway:migrate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/migration/dev
spring.flyway.clean-disabled=false